name: dyn_mouse_scroll
description: A wrapper for scrollable widgets that enables smooth scrolling with a mouse on all platforms.
version: 1.0.8
repository: https://github.com/Bluebar1/dyn_mouse_scroll

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




 
